// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igxauoyjttwtyujsoxjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneGF1b3lqdHR3dHl1anNveGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDQ4ODUsImV4cCI6MjA2NDg4MDg4NX0.2yHE-O-HJtS8DLcfF52IFT9YHhSejGRtmjfi4V7Uw9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);